### ISSUE TITLE
Disconnects on  Edimax EW-7822UAC

### ISSUE THREAD

**Issue by raqua** [Grawp/rtl8812au_rtl8821au#20]
Hi, 

I am running on Arch linux, but every about 20 minutes I get disconnected and can not reconnect. It will start working only after I physically disconnect the dongle and connect it back. 

Here is my dmesg log:
[dmesg.zip](https://github.com/Grawp/rtl8812au_rtl8821au/files/316976/dmesg.zip)

I was using this package before:
https://aur.archlinux.org/packages/rtl8812au_asus-dkms/
There was no such issue with that package, but it does not work with new kernel anymore. 

Please let me know if I can provide any more info to help get this solved. 
Thanks.

**Comment by jhonny-oliveira** [comment]
I'm facing the exact same problem. I tested several other rtl8812au found
in github on my Ubuntu 16.04 and faced the same problem.
I'm also available to provide any necessary logs.

Best regards,
Jhonny Oliveira

**Comment by zebulon2** [comment]
I have discussed this with Grawp on the AUR page. It turns out 4.3.22_beta is outdated compared to final 4.3.20 available on the Edimax EW-7822UAC support page. The Changelog in the 4.3.20 archive indicated that kernel panics were fixed in a 31st December 2015 release, which is posterior to the 4.3.22_beta and possibly the issue we are experiencing. I just tried yorkedork 4.3.20 branch fork available on Github. So far it works perfectly  with my 7822UAC. Furthermore, I am experiencing much less packet loss when pinging. Grawp has ackowledged the issue and stated he will include that 4.3.20 driver in his version soon.

**Comment by Grawp** [comment]
There's a new 4.3.20 branch in this repo. Please report whether the problem persists there.

**Comment by raqua** [comment]
Just tested it and in 5 minutes, I got disconnected twice. First time, it reconnected again after about 30 seconds, second time it just could not connect again.

**Comment by Grawp** [comment]
@raqua What chip do you have? 8821a or 8812a?

**Comment by raqua** [comment]
Dmesg shows: 
RTL871X: rtl8812au v4.3.20_16317.20160108

**Comment by Grawp** [comment]
@raqua Please provide lsusb output.

**Comment by raqua** [comment]
Bus 003 Device 002: ID 7392:a822 Edimax Technology Co., Ltd

**Comment by jhonny-oliveira** [comment]
For me the 4.3.20 solved the disconnects problem on 2.4GHz. 5G is also
improved, but still disconnects after a while. I did not have much time to
test this last issue, but as far as I could see, after it disconnects, I
can no longer reconnect...

Best regards,
Jhonny Oliveira

**Comment by mrpendulum** [comment]
I'm seeing this issue as well on 5GHz. Requires dongle removed and reinserted to resolve. Lucky to get 5 minutes uptime at this stage. The hardware is a Dlink DWA-182. Logs below:

> lsusb
Bus 001 Device 010: ID 2001:3315 D-Link Corp.

> dmesg
[  784.636201] RTL871X: rtw_dev_unload: driver not in IPS
[  786.024127] usb 1-9: new high-speed USB device number 10 using xhci_hcd
[  786.152549] usb 1-9: New USB device found, idVendor=2001, idProduct=3315
[  786.152555] usb 1-9: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  786.152558] usb 1-9: Product: D-Link Wireless Adapter
[  786.152560] usb 1-9: Manufacturer: Realtek
[  786.152562] usb 1-9: SerialNumber: 123456
[  786.244873] RTL871X: rtw_ndev_init(wlan1)
[  791.775975] RTL871X: rtw_set_802_11_connect(wlan1)  fw_state=0x00000008
[  791.885460] RTL871X: start auth
[  791.887170] RTL871X: auth success, start assoc
[  791.889483] RTL871X: rtw_cfg80211_indicate_connect(wlan1) BSS not found !!
[  791.889487] RTL871X: assoc success
[  791.894512] RTL871X: send eapol packet
[  791.903878] RTL871X: send eapol packet
[  791.903920] RTL871X: set pairwise key camid:4, addr:10:da:43:7c:67:4e, kid:0, type:AES
[  791.905051] RTL871X: set group key camid:5, addr:10:da:43:7c:67:4e, kid:1, type:AES
[  941.280909] RTL871X: linked_status_chk(wlan1) disconnect or roaming
[  948.682316] RTL871X: There are some pkts to transmit
[  948.682324] RTL871X: free_xmitbuf_cnt: 4, free_xmit_extbuf_cnt: 1
[  952.470407] RTL871X: There are some pkts to transmit
[  952.470410] RTL871X: free_xmitbuf_cnt: 4, free_xmit_extbuf_cnt: 0
[  954.474539] RTL871X: There are some pkts to transmit
[  954.474541] RTL871X: free_xmitbuf_cnt: 4, free_xmit_extbuf_cnt: 0
[  956.478497] RTL871X: There are some pkts to transmit
[  956.478500] RTL871X: free_xmitbuf_cnt: 4, free_xmit_extbuf_cnt: 0
[  961.162698] RTL871X: There are some pkts to transmit
[  961.162700] RTL871X: free_xmitbuf_cnt: 4, free_xmit_extbuf_cnt: 0
[  963.166682] RTL871X: There are some pkts to transmit
[  963.166684] RTL871X: free_xmitbuf_cnt: 4, free_xmit_extbuf_cnt: 0
[  967.895611] RTL871X: There are some pkts to transmit
[  967.895618] RTL871X: free_xmitbuf_cnt: 4, free_xmit_extbuf_cnt: 0
[  971.918893] RTL871X: There are some pkts to transmit
[  971.918897] RTL871X: free_xmitbuf_cnt: 4, free_xmit_extbuf_cnt: 0

Happy to provide more details if needed.

**Comment by JSkier21** [comment]
Also seeing disconnects on WUSB6300 @ 5ghz. Sometimes goes for an hour or two, others, minutes. Will try 2ghz and see if that is any better.
